### ISSUE TITLE
build tools doesn't point to Gradle build tools 2.4.0-alpha6

### ISSUE THREAD

**Issue by hannesa2** [originx/Gradle_troubles_android_enteprise#1]
Do use it as a repo to show errors to Android devs with problems concerning 2.4.0-alpha6 it doesn't fit the primary purpose when it points to
```
classpath 'com.android.tools.build:gradle:2.2.2' 
```

**Comment by hannesa2** [comment]
When we update to 2.4.0-alpha6 we run into this:
![image](https://cloud.githubusercontent.com/assets/3314607/25302149/f7c783e8-2737-11e7-9b61-c3acd02d4b4f.png)

**Comment by hannesa2** [comment]
see PR https://github.com/originx/Gradle_troubles_android_enteprise/pull/2 to fix

**Comment by originx** [comment]
Merged pr thanks
