### ISSUE TITLE
btw dex error during update of libs detected

### ISSUE THREAD

**Issue by hannesa2** [originx/Gradle_troubles_android_enteprise#14]
In our prod app, there is a PR of update libs which has a dex error, here I guess I found why.
When I update support lib to 27.1.1 I run into this too

> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForGlobalAustriaCompatDebug'.
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/hannes/git/Gradle_troubles_android_enteprise/app/build/intermediates/transforms/dexBuilder/globalAustriaCompat/debug/310.jar,.....

**Comment by originx** [comment]
Interesting we should try with 28 cannary and as cannary to see if issue is fixed there if not we can open a bug on Monday

**Comment by hannesa2** [comment]
let's see on Monday

**Comment by hannesa2** [comment]
https://issuetracker.google.com/issues/78853789

**Comment by originx** [comment]
https://github.com/originx/Gradle_troubles_android_enteprise/pull/18
resolved
